petik dihapus
Yoga-1508/Tugas1 pull request #1
Opened 2021-04-17 05:47 UTC by Yoga-1508

2021-04-17 06:16 UTC, r-ijal commented
isikan "hai fosan, selamat datang di github"

2021-04-17 06:36 UTC, r-ijal requested changes
isikan "Hai Yoga, selamat datang di FOSAN"

2021-04-19 03:58 UTC, r-ijal requested changes, later dismissed

2021-04-19 03:58 UTC, r-ijal commented on hello.txt
> +Hai Fosan,Selamat Datang Di GithubHai Fosan,Selamat Datang Di Github
ini di delete aja, pake yg di line 2

2021-04-19 04:01 UTC, Yoga-1508 commented on hello.txt
> +Hai Fosan,Selamat Datang Di GithubHai Fosan,Selamat Datang Di Github
sudah mas,dicommit yang "file sudah dirubah"

2021-04-19 04:05 UTC, r-ijal commented
Oke langsung di merge aja

2021-04-19 04:06 UTC, merged